name       :  redshift
version    : 1.10
release    : 1
source     :
    - https://github.com/jonls/redshift/archive/v1.10.tar.gz : f7a1ca1eccf662995737e14f894c2b15193923fbbe378d151e346a8013644f16
license    : GPL-3.0
summary    : Redshift adjusts the color temperature of your screen according to your surroundings. 
description: |
    Redshift adjusts the color temperature of your screen according to your surroundings. 
builddeps  :
    - pkgconfig(geoclue-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libdrm)
    - pkgconfig(python-3.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(xxf86vm)
    - pkgconfig(xcb-randr)
    - pyxdg
rundeps:
    - geoclue
    - python3
    - python3-gobject
    - pyxdg
setup      : |
    ./bootstrap
    %configure --disable-static --enable-drm  --enable-geoclue2 --enable-randr --enable-vidmode --with-systemduserunitdir=/etc/systemd/user/
build      : |
    %make
install    : |
    %make_install
