name       : redshift
version    : 1.11
release    : 3
source     :
    - https://github.com/jonls/redshift/archive/v1.11.tar.gz : a89cee0dc822fa2bfda0703d8ecedeccc08da3aebdf1880593f28da81c3dc879
license    : GPL-3.0
summary    : Redshift adjusts the color temperature of your screen according to your surroundings. 
description: |
    Redshift adjusts the color temperature of your screen according to your surroundings. 
builddeps  :
    - pkgconfig(geoclue-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libdrm)
    - pkgconfig(python-3.5)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(xxf86vm)
    - pkgconfig(xcb-randr)
    - pyxdg
rundeps:
    - geoclue
    - python3
    - python3-gobject
    - pyxdg
setup      : |
    ./bootstrap
    %configure --disable-static --enable-drm  --enable-geoclue2 --enable-randr --enable-vidmode --with-systemduserunitdir=/etc/systemd/user/
build      : |
    %make
install    : |
    %make_install
